version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: severnaya_korzina_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: severnaya_korzina
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # Adminer для управления БД (веб-интерфейс)
  adminer:
    image: adminer:4.8.1
    container_name: severnaya_korzina_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge